export const CHANGE_USER = 'CHANGE_USER';
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const LOAD_USER_ROOM = 'LOAD_USER_ROOM';
export const UPSERT_ROOM = 'UPSERT_ROOM';

export const ADD_SEARCH = 'ADD_SEARCH';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const RECEIVE_HOUSES = 'RECEIVE_HOUSES';
export const TAG_FAVORITE = 'TAG_FAVORITE';
export const FILTER_HOUSE = 'FILTER_HOUSE';
export const SELECT_HOUSE = 'SELECT_HOUSE';
