export const CHANGE_USER = 'CHANGE_USER';
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const LOAD_USER_ROOM = 'LOAD_USER_ROOM';
export const UPSERT_ROOM = 'UPSERT_ROOM';

export const ADD_SEARCH = 'ADD_SEARCH';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const RECEIVE_HOUSES = 'RECEIVE_HOUSES';
export const TAG_FAVORITE = 'TAG_FAVORITE';
export const FILTER_HOUSE = 'FILTER_HOUSE';
export const SELECT_HOUSE = 'SELECT_HOUSE';
export const UNSELECT_HOUSE = 'UNSELECT_HOUSE';
export const HOVER_HOUSE = 'HOVER_HOUSE';
export const SET_SORT = 'SET_SORT';
export const ADD_SEARCH_TERMS = 'ADD_SEARCH_TERMS';
export const SHOW_CLUSTER = 'SHOW_CLUSTER';
export const SET_CLUSTER = 'SET_CLUSTER';
export const SET_OUTLINE = 'SET_OUTLINE';
export const SET_HOUSES_ON_MAP = 'SET_HOUSES_ON_MAP';

// app
export const SHOW_PROGRESSBAR = 'SHOW_PROGRESSBAR';
export const SET_SNACKBAR = 'SET_SNACKBAR';

