// user
export const CHANGE_USER = 'CHANGE_USER';
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const LOAD_USER_ROOM = 'LOAD_USER_ROOM';
export const UPSERT_ROOM = 'UPSERT_ROOM';

// house
export const ADD_SEARCH = 'ADD_SEARCH';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const RECEIVE_HOUSES = 'RECEIVE_HOUSES';
export const TAG_FAVORITE = 'TAG_FAVORITE';
export const FILTER_HOUSE = 'FILTER_HOUSE';
export const SELECT_HOUSE = 'SELECT_HOUSE';
export const UNSELECT_HOUSE = 'UNSELECT_HOUSE';
export const UNSELECT_ALL_HOUSES = 'UNSELECT_ALL_HOUSES';
export const SELECT_HOUSES = 'SELECT_HOUSES';
export const UNSELECT_HOUSES = 'UNSELECT_HOUSES';
export const HOVER_HOUSE = 'HOVER_HOUSE';
export const SET_SORT = 'SET_SORT';
export const ADD_SEARCH_TERMS = 'ADD_SEARCH_TERMS';

// app
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

// share
export const SELECT_CUSTOMER = 'SELECT_CUSTOMER';
export const SELECT_CUSTOMERS = 'SELECT_CUSTOMERS';
export const UNSELECT_CUSTOMER = 'UNSELECT_CUSTOMER';
export const UNSELECT_CUSTOMERS = 'UNSELECT_CUSTOMERS';
export const SET_BY_FILTER = 'SET_BY_FILTER';
export const SET_SHARE_ID = 'SET_SHARE_ID';
export const SET_SHARE_EMAIL = 'SET_SHARE_EMAIL';
